---
swagger: "2.0"
info:
  description: "API description for project service"
  version: "1.0.0"
  title: "NodeJS AWS Project"
  contact:
    email: "diana_loika@epam.com"
host: "iydulbqdjk.execute-api.eu-west-1.amazonaws.com"
basePath: "/dev"
tags:
- name: "product-service"
  description: "serves products"
  externalDocs:
    description: "Read the task"
    url: "https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task3-product-api/task.md"
schemes:
- "https"
- "http"
paths:
  /products:
    get:
      tags:
      - "product-service"
      summary: "Get all products from the store"
      description: ""
      operationId: "getProducts"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "ProductService"
  /products/{productId}:
    get:
      tags:
      - "product-service"
      summary: "Find product by ID"
      description: "Returns a single product"
      operationId: "getProductById"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "ID of product to return"
        required: true
        type: "number"
        format: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      x-swagger-router-controller: "ProductService"
definitions:
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
      title:
        type: "string"
      price:
        type: "integer"
      count:
        type: "integer"
      description:
        type: "string"
      image:
        type: "string"
    example:
      image: "image"
      price: 6
      count: 1
      description: "description"
      id: 0
      title: "title"
