import { IProduct } from './model';

export const products: IProduct[] = [{
    title: 'Product-1',
    price: 123,
    image: '',
    count: 4,
    description: 'Short Product Description',
    id: 1,
}, {
    title: 'Product-2',
    price: 223,
    image: '',
    count: 4,
    description: 'Short Product Description',
    id: 2,
}, {
    title: 'Product-3',
    price: 323,
    image: '',
    count: 4,
    description: 'Short Product Description',
    id: 3,
}, {
    title: 'Product-4',
    price: 423,
    image: '',
    count: 4,
    description: 'Short Product Description',
    id: 4,
}, {
    title: 'Product-5',
    price: 523,
    image: '',
    count: 4,
    description: 'Short Product Description',
    id: 5,
}, {
    title: 'Product-6',
    price: 623,
    image: '',
    count: 4,
    description: 'Short Product Description',
    id: 6,
}, {
    title: 'Product-7',
    price: 723,
    image: '',
    count: 4,
    description: 'Short Product Description',
    id: 7,
}, {
    title: 'Product-8',
    price: 823,
    image: '',
    count: 4,
    description: 'Short Product Description',
    id: 8,
}, {
    title: 'Product-9',
    price: 923,
    image: '',
    count: 4,
    description: 'Short Product Description',
    id: 9,
}];
